---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Make sure exim4 is not installed
  apt: name=exim4 state=absent

- name: Check if postfix is on the system
  stat: path=/usr/sbin/postfix
  register: postfix_install_status

- name: Make sure debconf / debconf-utils are present
  apt: name="{{ item }}" state=present
  with_items:
    - debconf
    - debconf-utils

- name: Debconf set selections for postfix
  debconf:
    name: "postfix"
    question: "postfix/main_mailer_type"
    value: "No configuration"
    vtype: "select"
  when: postfix_install_status.stat.exists == false

- name: Install postfix and mailutils
  apt: name="{{ item }}" state=present
  with_items:
    - postfix
    - mailutils

- name: Configure /etc/mailname
  template:
    src: mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: Update configuration file
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: Start and enable postfix
  service:
    name: postfix
    state: started
    enabled: true

- name: Send testmail
  shell: "echo \"Test 1 2 3 4 5\" | mail -s \"Testmail\" {{ postfix_testmail_address }}"
  changed_when: false
  when: postfix_testmail_address is defined
